# Generated by Django 4.2.23 on 2025-08-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gamehistory",
            old_name="prise",
            new_name="prize",
        ),
    ]
