# Generated by Django 4.2.23 on 2025-08-21 11:25

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_prise_gamehistory_prize"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=20, unique=True, validators=[core.models.validate_phone]
            ),
        ),
    ]
